### ISSUE TITLE
Shobhika Devanagari Test File

### ISSUE THREAD

**Issue by gasyoun** [Sandhi-IITBombay/Shobhika#2] opened 2016-11-13 11:11 UTC
Namaste,

  Well done. Let me add a grain of salt and testing. Hope everything is clear from the files attached. 

[Shobhika Devanagari Test File.pdf](https://github.com/Sandhi-IITBombay/Shobhika/files/587712/Shobhika.Devanagari.Test.File.pdf)

[Liste-807-Sanskrit-Ligaturen_Shobhika.pdf](https://github.com/Sandhi-IITBombay/Shobhika/files/587713/Liste-807-Sanskrit-Ligaturen_Shobhika.pdf)

Shobhika Devanagari Test File

न्द्ध न्द्व ब्ल ज्ज्ञ ल्भ ल्भ्य ञ्श्व
कार्येकर्ये क्षा
सु॒ ह्वा॒ ङ्क्षा दीदा॒ ह्वा॒ दा॒न॒शा॒र्दी॑
र्ते
ए॒व पर्यै॑मि सं ग॑च्छध्वं पूर्वे॑ रि॑ र्तिं॑ वि
रृरॄरॢरॣ केफे ते॑तै॑र्त॑तं॑तँ॑
र्क्ति रि र्तिं र्केर्फैँकेफेँ॑र्कें॑
र्ततेर्तँतेर्तै॑र्तैँ र्तें॑ र्तीं॑ र्तिं॑
ग्तेतेहग्ते एर्त
द र्तोर्तौ र्तों
तंतँतेतैतोतौतंतःतॅतोतौ
र्तंर्तँ र्तेर्तै र्ते र्तैर्तोतौतंतःतॅतोतौ
र्ते तिँ तँ र्तॅं र्ति री
र्किर्कीर्के र्तिर्सिर्विर्रि र्रर्चिर्किर्फिर्टि
र्क्पिं॑र्र्स् र्च्मिं स्ति
र्कु॒ ट्रृ द द़ु
द्ध्य द्ध्व न्द न्द्र त्न्य रृरॄरॢरॣ
ग्र्य त्र्य द्द्व द्द्र
छुछ्रुझुझ्रुक्कुक्चुक्वु
ङ्कुङ्क्तुङ्क्षुङ्खुङ्गुर्ङ्ग्रंर्ङ्घें॒ङ्घ्रुङ्मुङ्युच्छुच्छ्रुछ्वुच्छ्वु
ट्टु ट्वुट्शुड्गुड्ग्रुड्घुड्घ्रु
द्गुद्घुद्घ्रु द्दु द्द्रु द्द्वु  द्धुद्ध्रुद्ध्युद्ध्वुद्बुद्भुद्भ्रुद्भ्युद्वुद्व्यु
ष्ट्वु  क्कृ
ह्नु  ह्न्युह्लुह्ल्युह्वुह्व्युह्मुह्यु
द्  न्द् ब्द् द्र् छृ ट्र्य
ङुटुठुडुढु
ङ् ट् ठ् ड् ढ्
क् ट्यट्र्य
र्क र्ति र् 
कुक ङ् ङ्कुङ्क्ङ्कूङ्कृ द् ष्ट् ह् ह्म् ष्ट्य
क्कू क्त्र क् क क त़
द्ग्द्ध् द्धृ द्दू द्मू
ट्य ट्र्य ड्र्य क्र्य च्छ् द्य क्य द्व्य
ङ्ख्य छ्ख्य ङ्क्क्य
न्न्य्व न्न्व्य् द्ध्
द्ध्य द्ध्य ङ्क्ष ङ्क्त ङ्क्
च्छ्व
द्र्य द्र्य द्भ्य द्व्य
ष्ट्व ष्ट्य द्घ्र ह्न्य द्व्य द्द्व
न्द्र न्द्ध
न्ध स्त्य न्त्र्य त्न्य क्र्य द्र्त्स
क्र्य ल्र्व त्र्न्य द्र्य द्र्व्य ढ्र्य
कखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह
क्षज्ञक्र्य
क्रख्रग्रघ्रङ्रच्रछ्रज्रझ्रञ्रट्रठ्रड्रढ्रण्रत्रथ्रद्रध्रन्रप्रफ्रब्रभ्रम्रय्रर्रल्रव्रश्रष्रस्रह्र
क्ष्रज्ञ्र
क्र्व
क्र्य द्द्व क्र्य
क्र्य च्र्यक्र्य च्र्
क्र्य
कुफु क॒र्चि र्वि शु  शृ शॄ
क्र्
कि
क्र र्क र्म र्ल
व्र्य द्र्व्
द्र्य
र्द्व्
ङुशु
छु
क्तॄ

**Comment by ijya** [comment] 2016-11-13 15:03
Thanks for testing the font and sharing your comments. Suggestions related to coding will be incorporated in the next release of the font. Suggestions related to design of glyphs might not be taken up immediately.

Can you please also point out what we should look for in the second file? It is not clear what the issue is.

**Comment by gasyoun** [comment] 2016-11-13 18:34
> Suggestions related to coding will be incorporated in the next release of the font

Thanks.

> Suggestions related to design of glyphs might not be taken up immediately.

That I can understand.

> what we should look for in the second file? 

You can see for many ligatures used in Sanskrit what would be a better solution for a ligature. If you declare it's not only Sanskrit, but Vedic as well, there should be a nice set of ligatures. So you can see how the ligatures look in fonts that support Devanagari for Sanskrit in a smoother way (in a few cases).

Here I made one more files - all ligatures from Rigveda, so it's a simple list, but some solutions are not optimal, @ijya and @girish-dalvi agree?

[Liste-460-Rigveda-Ligaturen-Statistik_Shobhika.pdf](https://github.com/Sandhi-IITBombay/Shobhika/files/587959/Liste-460-Rigveda-Ligaturen-Statistik_Shobhika.pdf)

**Comment by vysogot** [comment] 2016-11-17 09:02
Hello. The font looks amazing. Is there any was I can convert my files which use "RM Devanagari" font to it? Are you aware of any converter? Thank you for suggestions. Just to give you an idea. When I select RM Devanagari text: pratyayah parah (in script, in Word application), and pick Shobhika font it gives me: ‘atyaya: par": 

Also, how to type in compound letters, like: ष्ठ. What combination of keys I need to press and in what sequence to make it.

**Comment by ijya** [comment] 2016-11-19 15:45
Please share the details of the format of your files and operating system.

**Comment by vysogot** [comment] 2016-11-19 15:50
That is Windows 10 and Microsoft Word file format.

2016-11-19 21:15 GMT+05:30 ijya notifications@github.com:

**Comment by ijya** [comment] 2016-11-19 15:59
Well, why do you need any converter in that case? Can you not select the text and change the font to Shobhika?

**Comment by ijya** [comment] 2016-11-19 16:11
Can you share a sample document so I can see what the problem is? For typing compound characters, you will have to select a Devanagari keyboard in Windows (search Keyboard in Start menu). Once you select the keyboard, it will show you which key gives which character. To type ष्ठ, you will have to type ष +  ्  + ठ. Hope this helps.

**Comment by gasyoun** [comment] 2016-11-19 21:37
> ष + ् + ठ. 

Virama is the key component here.

**Comment by vysogot** [comment] 2016-12-02 02:14
Thank you. Is it possible that you create another font, like "Shobhika
Transcription" in which you can write in latin transcript and then mark all
text, select "Shobhika" and have it in Devanagari? Or does it already work
like this with some other font?

2016-11-20 3:07 GMT+05:30 Marcis Gasuns <notifications@github.com>:

**Comment by ijya** [comment] 2016-12-02 16:39
Transcription is independent of the font. If you use latex, you can try using the velthuis pre-processor which does something like what you are asking. Else you can use a number of online tools for transforming Latin input into Devanagari.

**Comment by vidyajay** [comment] 2016-12-07 13:40
Many thanks to the creators of this well-thought out and well-designed font . It would be very helpful if there is a keyboard layout - for mac and windows. Alternately, if there is some documentation provided in the form of an encoding table or a mapping/list of characters/glyphs, then people could create their own inputmethods / keyboardlayout.

**Comment by nomoon** [comment] 2016-12-08 06:47
@vidyajay Since the font operates using Unicode code-points, any existing Devanagari keyboard layout for Mac or Windows and and most input systems should operate as expected.

**Comment by vidyajay** [comment] 2016-12-08 14:59
@nomoon Yes, Have been using the extended Devanagari and other keyboard layouts. This  question is specific to vaidika accents and symbols provided here such as specific suklayajurveda varieties of anusvara - nagamukha, vamamukha, pushpika etc.  I wanted to check if there exists a keyboard layout file before extending an existing one to facilitate typing of these characters..

**Comment by ijya** [comment] 2016-12-09 08:27
@vidyajay Thanks for the appreciation. As far as I am aware, the default keyboards in Mac and Windows (and Linux) do not support vedic accents. If you are not going to use the vedic accents heavily, then it may be simplest to input the characters using their Unicode hexadecimal values. Each operating system has its own way of doing this. If you are going to use the  accents frequently, you may require to create a custom keyboard suitable for your purpose. On Mac this is very easy with Ukelele - http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele
In Linux too, this is usually as easy as modifying a text file. However, this may be distro dependent.  On Windows, you may try your luck with the Microsoft Keyboard Layout creator-https://www.microsoft.com/en-us/download/details.aspx?id=22339&ppud=4

**Comment by ijya** [comment] 2017-01-24 09:11
@gasyoun Some of the bugs pointed out by you have been fixed in v1.04. Please test it.

**Closed as completed** 2017-01-25 13:05 UTC
