### ISSUE TITLE
Serious bug

### ISSUE THREAD

**Issue by mpdasa** [Sandhi-IITBombay/Shobhika#1] opened 2016-11-03 01:09 UTC
I checked new font. It has one serious bug. When I type any ligature (द्य for example) and after that I put virama, then ligature breaks up in two separate symbols with viramas. The font is therefore virtually unusable.

**Comment by ijya** [comment] 2016-11-03 16:23
Hi,

Can you please give the following details:
1. Actual use case - Which word would you like to type which is displaying the above bug?
2. Details of operating system and application used to test the font.

Thanks

**Comment by ijya** [comment] 2016-11-09 12:26
As we are unable to reproduce the bug, and in absence of further information, this issue is being marked closed.

**Comment by kalapi** [comment] 2016-11-10 18:31
Hello @ijya, 

I tried to replicate the bug and found that a Virama at the end of a conjunct cluster does indeed 'decompose' it. (Murty Sanskrit is shown for comparison; tested on Google Chrome Version 54.0.2840.71 [64-bit] on Mac OS 10.11.6 )

<img width="381" alt="screen shot 2016-11-10 at 11 57 56 pm" src="https://cloud.githubusercontent.com/assets/15804460/20189149/dd9c5540-a7a1-11e6-9af9-e78e53b01290.png">
<img width="377" alt="screen shot 2016-11-10 at 11 58 08 pm" src="https://cloud.githubusercontent.com/assets/15804460/20189138/d6bf8aa8-a7a1-11e6-9c51-6639f8259689.png">

**Comment by ijya** [comment] 2016-11-11 09:16
Reopening issue.

**Comment by ijya** [comment] 2016-11-12 13:30
Thanks for reporting the bug. This issue has been fixed in version 1.01.

**Closed as completed by ijya** 2016-11-12 13:30 UTC
