### ISSUE TITLE
शृ in Shobika

### ISSUE THREAD

**Issue by Nadadur** [Sandhi-IITBombay/Shobhika#9] opened 2018-03-02 07:55 UTC
When I want   " "s.r "  (sru in skt)  it comes as   शृङ्गार in Shobika. But
it should have श and not श्र. Can you please help ?

**Comment by ijya** [comment] 2018-03-07 05:11
@Nadadur This is not a bug. This is how श + ृ = शृ is traditionally represented in most Sanskrit manuscripts, as well as printed works. While you desire the more modern representation of this character, Shobhika follows the traditional representation. Note that this character is missing the oblique stroke in the bottom half of श्र which is representative of र. Therefore, it is श + ृ and not श्र + ृ.

**Comment by Nadadur** [comment] 2018-03-07 06:18
My request is can't we have  शृ also in Shobika ?

On 7 Mar 2018 10:41, "ijya" <notifications@github.com> wrote:

@Nadadur <https://github.com/nadadur> This is not a bug. This is how श + ृ
= शृ is traditionally represented in most Sanskrit manuscripts, as well as
printed works. While you desire the more modern representation of this
character, Shobhika follows the traditional representation. Note that this
character is missing the oblique stroke in the bottom half श्र which is
representative of र. Therefore, it is श + ृ and not श्र + ृ.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sandhi-IITBombay/Shobhika/issues/9#issuecomment-371024849>,
or mute the thread

**Comment by Nadadur** [comment] 2018-03-07 06:44
*What I meant was can't we have  श with the .r vowel in Shobika ?*

**Comment by ijya** [comment] 2018-03-07 07:35
@Nadadur This is currently not implemented in Shobhika. We can consider implementing it in the next version if there is a pressing need. What is your use case?

**Comment by Nadadur** [comment] 2018-03-07 17:18
Seven of my wife's original works in Sanskrit are being published online in
sankritdocuments.org (more are to follow). Fyi, the scanned versions are
already available: https://sanskritdocuments.org/sites/pushpasrivatsan

We were not very happy with the font they were using and so requested them
to use Shobhika, which we feel is the best. But in the case of "s.r, we
feel the representation "sa with a curve below is more appropriate (just
like k.r is ka with a curve below and not k with a curve below; similarly
other consonants) . Also old editions of the dictionaries by Apte and
Monier Williams use the whole letter शृ, and not the character without the
oblique stroke in the bottom half श्र with a curve below.

Hence request you to implement the same currently.

Best Wishes,
Vathsan







On 7 Mar 2018 13:05, "ijya" <notifications@github.com> wrote:

@Nadadur <https://github.com/nadadur> This is currently not implemented in
Shobhika. We can consider implementing it in the next version if there is a
pressing need. What is your use case?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sandhi-IITBombay/Shobhika/issues/9#issuecomment-371050096>,
or mute the thread

**Comment by Nadadur** [comment] 2018-03-12 11:01
The letters    , ,    etc. are   + र ,  + ल,   + व   and so on. They are
compound letters. In prosody the
 joins the previous letter and makes it long.   Whereas      is a single
whole letter counted as one  in prosody, just as श, शि and शु . Hence it is
wrong to represent it as a compound letter. It should only be written as  .


Surely the ancient scholars would have written it only like this in their
manuscripts.  In print it might have appeared as the compound letter. As I
already mentioned in my previous mail old grammar books and dictionaries by
Apte and Monier-Williams use only  the whole letter    , and not the other
way.

Hence I request you to change the font so that my wife's books have the
correct version.

**Comment by jamadagni** [comment] 2019-05-10 08:42
The previous post of @Nadadur contains many gaps. Perhaps he was trying to copy-paste text interspersed with images?

Anyhow, de gustibus non est disputandum. With all due respect, this is an individual typographical preference which should not be fixed in the font. Popular freely available Devanagari fonts do present the श in śṛ as the श्र ligature minus the bottom diagonal. See below.

And the current font itself (like other popular fonts) supports the desired presentation. All one has to do is insert a ZWJ or ZWNJ between the base and the vowel sign. Also see below.

![Screenshot_20190510_140306](https://user-images.githubusercontent.com/948170/57513752-9f4eaf00-732c-11e9-9396-536c26f6dff8.png)

At least this works for me on LibreOffice 6.1 on Kubuntu 18.04.

ODT file for producing above table: [shr.zip](https://github.com/Sandhi-IITBombay/Shobhika/files/3165879/shr.zip)

**Comment by ijya** [comment] 2019-05-10 10:04
@jamadagni Thanks for pointing this out. I have tested this at my end and it indeed works.  The desired output can be obtained by typing either of the following sequence of characters: 

1. श + zero-width joiner +  ृ
2. श + zero-width non-joiner +  ृ

For future reference, the zero-width joiner can be input using its hexadecimal code `U200D`. The zero-width non-joiner can be input using the hexadecimal code `U200C`. 

As this is an adequate solution, I will mark the issue as closed.

**Closed as completed by ijya** 2019-05-10 10:04 UTC

**Comment by Nadadur** [comment] 2019-05-11 02:48
Thanks a lot for your reply
